import Riemann.Basic.FiniteOperatorParameter
import Riemann.Analysis.FiniteWindow.KilledShiftHilbert
import Riemann.Arithmetic.MultiplicativeShift
import Riemann.Arithmetic.FiniteSynthesis
import Riemann.Arithmetic.FiniteEulerProduct
import Mathlib.Analysis.SpecialFunctions.ExpDeriv
import Mathlib.Analysis.Complex.RealDeriv

/-! # Finite Euler synthesis on the genuine interval Hilbert space

The representation consists of the actual killed shifts. The frozen finite
Dirichlet algebra proves its Euler and Möbius identities in the commutative
image algebra; no multiplication or inversion is moved through a projection.
-/

noncomputable section
open scoped NNReal
open Finset

namespace Riemann.Analysis.FiniteWindow

local instance (L : ℝ) : ContinuousSMul ℝ (Hilbert L →L[ℂ] Hilbert L) :=
  IsScalarTower.continuousSMul ℂ

/-- Positive natural indices act by their actual logarithmic killed shifts. -/
def primeShift (L : ℝ) : ℕ →*₀ (Hilbert L →L[ℂ] Hilbert L) where
  toFun n := if n = 0 then 0 else killedShift L (Arithmetic.natLog n)
  map_zero' := by simp
  map_one' := by simp [Arithmetic.natLog_one, killedShift_zero]; rfl
  map_mul' m n := by
    by_cases hm : m = 0
    · subst m; simp
    by_cases hn : n = 0
    · subst n; simp
    simp only [mul_eq_zero, hm, hn, or_self, ↓reduceIte, Arithmetic.natLog_mul hm hn]
    exact (killedShift_add L _ _).symm

theorem primeShift_killed (L : ℝ) {n : ℕ} (h : Real.exp L ≤ (n : ℝ)) :
    primeShift L n = 0 := by
  have hn : 0 < (n : ℝ) := (Real.exp_pos L).trans_le h
  have hn0 : n ≠ 0 := by exact_mod_cast hn.ne'
  change (if n = 0 then 0 else killedShift L (Arithmetic.natLog n)) = 0
  rw [if_neg hn0]
  apply killedShift_eq_zero
  rw [Arithmetic.natLog_coe hn0]
  exact (Real.le_log_iff_exp_le hn).mpr h

/-- Commutative algebra generated by the actual Hilbert-space shifts. -/
def primeAlgebra (L : ℝ) : Subalgebra ℂ (Hilbert L →L[ℂ] Hilbert L) :=
  Algebra.adjoin ℂ (Set.range (primeShift L))

instance primeAlgebra_comm (L : ℝ) : IsMulCommutative (primeAlgebra L) :=
  Algebra.isMulCommutative_adjoin ℂ (by
    rintro _ ⟨m, rfl⟩ _ ⟨n, rfl⟩
    rw [← map_mul, ← map_mul, Nat.mul_comm])

open scoped IsMulCommutative in
instance primeAlgebra_commRing (L : ℝ) : CommRing (primeAlgebra L) := inferInstance

def primeCharacter (L : ℝ) : ℕ →*₀ primeAlgebra L where
  toFun n := ⟨primeShift L n, Algebra.subset_adjoin ⟨n, rfl⟩⟩
  map_zero' := by ext; simp
  map_one' := by ext; simp
  map_mul' m n := by ext; simp

def primeWeight (L : ℝ) (σ : ℝ) : ℕ →*₀ primeAlgebra L :=
  ((algebraMap ℂ (primeAlgebra L)).toMonoidWithZeroHom.comp
    (Arithmetic.dirichletWeight (σ : ℂ))) * primeCharacter L

/-- An inclusive cutoff guaranteed to contain every nonzero represented term. -/
def primeCutoff (L : ℝ) : ℕ := ⌈Real.exp L⌉₊

theorem primeWeight_killed (L σ : ℝ) {n : ℕ} (hn : primeCutoff L < n) :
    primeWeight L σ n = 0 := by
  have hcut : Real.exp L ≤ (n : ℝ) :=
    (Nat.le_ceil (Real.exp L)).trans (by exact_mod_cast hn.le)
  apply Subtype.ext
  change Arithmetic.dirichletWeight (σ : ℂ) n • primeShift L n = 0
  rw [primeShift_killed L hcut]
  ext u
  simp

theorem primeCutoff_pos (L : ℝ) : 1 ≤ primeCutoff L :=
  Nat.one_le_iff_ne_zero.mpr (Nat.ceil_pos.mpr (Real.exp_pos L)).ne'

def primeOperator (L σ : ℝ) : Hilbert L →L[ℂ] Hilbert L :=
  (Arithmetic.eulerSynthesis (primeCutoff L) (primeWeight L σ) : primeAlgebra L)

def primeInverse (L σ : ℝ) : Hilbert L →L[ℂ] Hilbert L :=
  (Arithmetic.moebiusInverse (primeCutoff L) (primeWeight L σ) : primeAlgebra L)

def primeDerivative (L σ : ℝ) : Hilbert L →L[ℂ] Hilbert L :=
  (Arithmetic.eulerCoefficientDerivative (primeCutoff L) (primeWeight L σ) : primeAlgebra L)

def primeCurrent (L σ : ℝ) : Hilbert L →L[ℂ] Hilbert L :=
  (Arithmetic.synthesis (primeCutoff L) (primeWeight L σ)
    ArithmeticFunction.vonMangoldt : primeAlgebra L)

theorem primeInverse_mul (L σ : ℝ) : primeInverse L σ * primeOperator L σ = 1 := by
  exact congrArg Subtype.val (Arithmetic.moebiusInverse_mul_eulerSynthesis
    (primeCutoff L) (primeCutoff_pos L) (primeWeight L σ) (fun n hn => primeWeight_killed L σ hn))

theorem primeOperator_mul_inverse (L σ : ℝ) : primeOperator L σ * primeInverse L σ = 1 := by
  exact congrArg Subtype.val (Arithmetic.eulerSynthesis_mul_moebiusInverse
    (primeCutoff L) (primeCutoff_pos L) (primeWeight L σ) (fun n hn => primeWeight_killed L σ hn))

theorem prime_negative_logarithmic_derivative (L σ : ℝ) :
    -(primeInverse L σ * primeDerivative L σ) = primeCurrent L σ := by
  exact congrArg Subtype.val (Arithmetic.logarithmicCurrent (primeCutoff L) (primeWeight L σ)
    (fun n hn => primeWeight_killed L σ hn))

theorem primeWeight_coe (L σ : ℝ) {n : ℕ} (hn : n ≠ 0) :
    (primeWeight L σ n : Hilbert L →L[ℂ] Hilbert L) =
      Complex.exp (-(σ : ℂ) * (Real.log n : ℂ)) • primeShift L n := by
  change Arithmetic.dirichletWeight (σ : ℂ) n • primeShift L n = _
  simp [Arithmetic.dirichletWeight, hn]

theorem prime_synthesis_sum (L σ : ℝ) (f : ArithmeticFunction ℝ) :
    ((Arithmetic.synthesis (primeCutoff L) (primeWeight L σ) f : primeAlgebra L) : Hilbert L →L[ℂ] Hilbert L) =
      ∑ n ∈ Ioc 0 (primeCutoff L),
        (f n : ℂ) • (Complex.exp (-(σ : ℂ) * (Real.log n : ℂ)) • primeShift L n) := by
  change (primeAlgebra L).val (Arithmetic.synthesis (primeCutoff L) (primeWeight L σ) f) = _
  rw [Arithmetic.synthesis, map_sum]
  apply Finset.sum_congr rfl
  intro n hn
  rw [Arithmetic.twist_apply, map_mul]
  change (f n : ℂ) • (primeWeight L σ n : Hilbert L →L[ℂ] Hilbert L) = _
  rw [primeWeight_coe L σ (ne_of_gt (mem_Ioc.mp hn).1)]

theorem primeOperator_sum (L σ : ℝ) :
    primeOperator L σ = ∑ n ∈ Ioc 0 (primeCutoff L),
      Complex.exp (-(σ : ℂ) * (Real.log n : ℂ)) • primeShift L n := by
  change ((Arithmetic.eulerSynthesis (primeCutoff L) (primeWeight L σ) : primeAlgebra L) :
    Hilbert L →L[ℂ] Hilbert L) = _
  rw [Arithmetic.eulerSynthesis_sum]
  change (primeAlgebra L).val (∑ n ∈ Ioc 0 (primeCutoff L), primeWeight L σ n) = _
  rw [map_sum]
  apply Finset.sum_congr rfl
  intro n hn
  exact primeWeight_coe L σ (ne_of_gt (mem_Ioc.mp hn).1)

theorem primeDerivative_sum (L σ : ℝ) :
    primeDerivative L σ = ∑ n ∈ Ioc 0 (primeCutoff L),
      (-(Real.log n : ℂ) * Complex.exp (-(σ : ℂ) * (Real.log n : ℂ))) • primeShift L n := by
  change ((-Arithmetic.synthesis (primeCutoff L) (primeWeight L σ) ArithmeticFunction.log :
    primeAlgebra L) : Hilbert L →L[ℂ] Hilbert L) = _
  rw [Subalgebra.coe_neg, prime_synthesis_sum, ← Finset.sum_neg_distrib]
  apply Finset.sum_congr rfl
  intro n hn
  simp only [ArithmeticFunction.log_apply, mul_smul]
  apply ContinuousLinearMap.ext
  intro u
  simp only [neg_apply, smul_apply]
  module

theorem hasDerivAt_primeOperator (L σ : ℝ) :
    HasDerivAt (primeOperator L) (primeDerivative L σ) σ := by
  rw [primeDerivative_sum]
  have hf : primeOperator L = fun s : ℝ => ∑ n ∈ Ioc 0 (primeCutoff L),
      Complex.exp (-(s : ℂ) * (Real.log n : ℂ)) • primeShift L n :=
    funext (primeOperator_sum L)
  rw [hf]
  apply Riemann.Basic.hasDerivAt_operator_sum
  intro n hn
  have he := ((Complex.ofRealCLM.hasDerivAt (x := σ)).neg.mul_const (Real.log n : ℂ)).cexp
  convert! he using 1
  simp only [Complex.ofRealCLM_apply, Complex.ofReal_one, Pi.neg_apply]
  ring

/-- The original finite prime product on the actual commutative image algebra. -/
theorem primeOperator_euler_product (L σ : ℝ) : primeOperator L σ =
    (((∏ p ∈ Nat.primesBelow (primeCutoff L + 1),
      ∑ k ∈ range (primeCutoff L + 1), (primeWeight L σ p) ^ k) : primeAlgebra L) :
        Hilbert L →L[ℂ] Hilbert L) := by
  change (primeAlgebra L).val (Arithmetic.eulerSynthesis (primeCutoff L) (primeWeight L σ)) = _
  rw [Arithmetic.eulerSynthesis_sum, Arithmetic.finiteEuler_factorization
    (primeWeight L σ) (primeCutoff L) (fun n hn => primeWeight_killed L σ hn)]
  rfl

end Riemann.Analysis.FiniteWindow
